export const SET_USER_DATA = "SET USER DATA";
export const SET_GUEST_USER_DATA = "SET GUEST USER";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const RESET_STATE_AFTER_LOGOUT = "RESET_STATE_AFTER_LOGOUT";
export const FETCH_ALL_LABELS = "FETCH_ALL_LABELS";