export const SET_MAIN_ROUTE = 'SET_MAIN_ROUTE';

export const SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE';
export const SET_SELECTED_SUB_FEATURE = 'SET_SELECTED_SUB_FEATURE';

export const ADD_TO_OPEN_TABS = 'ADD_TO_OPEN_TABS';
export const REMOVE_FROM_OPEN_TABS = 'REMOVE_FROM_OPEN_TABS';

export const ADD_TO_MAP_TRAIL = 'ADD_TO_MAP_TRAIL';
export const REMOVE_FROM_MAP_TRAIL = 'REMOVE_FROM_MAP_TRAIL';

export const ADD_TO_OPEN_FEATURES = 'ADD_TO_OPEN_FEATURES';
export const REMOVE_FROM_OPEN_FEATURES = 'REMOVE_FROM_OPEN_FEATURES';

export const ADD_TO_MODULES = 'ADD_TO_MODULES';
export const REMOVE_FROM_MODULES = 'REMOVE_FROM_MODULES';

export const ADD_TO_PINNED_MODULES = 'ADD_TO_PINNED_MODULES';
export const REMOVE_FROM_PINNED_MODULES = 'REMOVE_FROM_PINNED_MODULES';