export const ADD_ROUTE = 'ADD_ROUTE';
export const REMOVE_ROUTE = 'REMOVE_ROUTE';
export const SET_MAIN_ROUTE = 'SET_MAIN_ROUTE';

export const SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE';
export const SET_SELECTED_SUB_FEATURE = 'SET_SELECTED_SUB_FEATURE';

export const ADD_TO_OPEN_TABS = 'ADD_TO_OPEN_TABS';
export const REMOVE_FROM_OPEN_TABS = 'REMOVE_FROM_OPEN_TABS';

export const ADD_TO_MAP_TRAIL = 'ADD_TO_MAP_TRAIL';
export const REMOVE_FROM_MAP_TRAIL = 'REMOVE_FROM_MAP_TRAIL';

export const ADD_TO_OPEN_FEATURES = 'ADD_TO_OPEN_FEATURES';
export const REMOVE_FROM_OPEN_FEATURES = 'REMOVE_FROM_OPEN_FEATURES';