
export const FETCH_USER_FEATURES_ERROR = "FETCH_USER_FEATURES_ERROR";
export const FETCH_USER_FEATURES_SUCCESS = "FETCH_USER_FEATURES_SUCCESS";
export const FETCH_MODULE_DATA_SUCCESS = "FETCH_MODULE_DATA_SUCCESS";
export const FETCH_MODULE_DATA_ERROR = "FETCH_MODULE_DATA_ERROR";
export const FETCH_FEATURE_MODULES_SUCCESS = "FETCH_FEATURE_MODULES_SUCCESS";
export const FETCH_FEATURE_MODULES_ERROR = "FETCH_FEATURE_MODULES_ERROR";
export const SET_SELECTED_MODULE = "SET_SELECTED_MODULE";
export const SET_SELECTED_FEATURE = "SET_SELECTED_FEATURE";

export const ADD_TO_BREADCRUMBS = "ADD_TO_BREADCRUMBS";
export const REMOVE_FROM_BREADCRUMBS = "REMOVE_FROM_BREADCRUMBS";

export const ADD_TO_OPENTABS = "ADD_TO_OPENTABS";
export const REMOVE_FROM_OPENTABS = "REMOVE_FROM_OPENTABS";

export const PUT_MAP_CLICK_DATA_IN_FEATURES = "PUT_MAP_CLICK_DATA_IN_FEATURES";

export const ADD_TO_PINNED_MODULES = "ADD_TO_PINNED_MODULES";
export const REMOVE_FROM_PINNED_MODULES = "REMOVE_FROM_PINNED_MODULES";

export const OPEN_PINNED_MODULE = "OPEN_PINNED_MODULE";

// export const SELECT_SPECIFIC_MODULE = "SELECT_SPECIFIC_MODULE";
// export const SHOW_SELECTED_FEATURE = "SHOW_SELECTED_FEATURE";

// export const PUT_TABBAR_FEATURES = "PUT_TABBAR_FEATURES";
// export const SET_LAST_MODULECODE_SUCCESS = "SET_LAST_MODULECODE_SUCCESS";
// export const DELETE_TAB_FROM_TABBAR = "DELETE_TAB_FROM_TABBAR";
// export const PUT_MAP_CLICK_DATA_IN_FEATURES = "PUT_MAP_CLICK_DATA_IN_FEATURES";
// export const SELECT_MODULE_AS_PINNED = "SELECT_MODULE_AS_PINNED";
// export const REMOVE_MODULE_AS_PINNED = "REMOVE_MODULE_AS_PINNED";
// export const REMOVE_MODULE_FROM_DELETED = "REMOVE_MODULE_FROM_DELETED";
// // export const RESET_STATE_AFTER_LOGOUT = "RESET_STATE_AFTER_LOGOUT";
// export const PUT_BREADCRUMS_MODULES = "PUT_BREADCRUMS_MODULES";
// export const ONCLICK_REFRESH_MODULE = "ONCLICK_REFRESH_MODULE";
export const REMOVE_REFRESH_MODULE = "REMOVE_REFRESH_MODULE";
// export const SHOW_DIRECT_FINAL_MODULE = "SHOW_DIRECT_FINAL_MODULE";
// export const CLEAR_PINNED_MODULES = "CLEAR_PINNED_MODULES";